#!/bin/bash

ida=$(find vuln-software-wo-optimizers -type d -name IDA)

for line in $ida
do
	name=$(echo $line | cut -d '/' -f 2)
	echo "[+] Flawfinder: $name"

	cd $line
	flawfinder --context --columns --html src_IDA > flawfinder/results.html && flawfinder --csv src_IDA > flawfinder/results.csv
	cd - 1> /dev/null
done
